SELECT_JOB = "//*[@href='/jobs']"
CREATE_JOB = "//button[normalize-space()='Create Job']"
JOB_NAME = "//input[@placeholder='Job Name']"
JOB_NUMBER = "//input[@placeholder='Job Number']"
DUE_DATE = "//input[@class='date-picker']"
JOB_SITE = "//input[@placeholder='Job Site Address']"
FLOAT_MODE = "//div[@class='wizard-content-label float-mode']/span"
CITY = "//input[@placeholder='City']"
STATE = "//input[@placeholder='State']"
ZIP_CODE = "//input[@placeholder='Zip Code']"
BUDGET_HOURS = "//input[@placeholder='Budget Hours']"
NEXT = "//div[contains(text(),'Next')]//*[name()='svg']"
COST_CODE = "//input[@placeholder='Cost Code']"
AREA = "//input[@placeholder='Area']"
DESCRIPTION = "//input[@placeholder='Description']"
BUDGET_COST = "//input[@placeholder='Budgeted Cost']"
TYPE = "//select[@class='sc-dkPtRN dBqbgo']"
ADD_COST_CODE = "//label[@class='wizard-content-label']/button"
PACKG_NAME = "//input[@placeholder='Package Name']"
WORKFLOW = "//select[@class='sc-dkPtRN dBqbgo']"
SELECT_PACKAGE = "//select[@class='sc-dkPtRN dBqbgo']"
PACKG_NUMBER = "//input[@placeholder='Package Number']"
PREVIOUS = "//div[@class='stepper-buttons']//div[1]"
CANCEL = "//button[normalize-space()='Cancel Job']"
ALERT = "//button[normalize-space()='Yes, cancel it!']"
CHOOSEFILE = "//input[@placeholder='No File Selected']"
UPLOAD = "//button[@class='sc-bdvvtL fSpYde upload']"
UPLOAD_DRAWING = "//button[normalize-space()='Upload Drawings']"
CHOOSEDRAWNFILE = "//input[@accept='.pdf']"
UPLOADDRAWNFILE = "//button[normalize-space()='Upload']"
SELECT_PACK = "//select[@class='sc-dkPtRN dsZUgO']"
ADD_NEW_ITEM = "//button[normalize-space()='Add New Item']"
MATERIAL = "//*[@id='root']/div[5]/div/div[2]/div/div[2]/div/div/div[2]/div[2]/div[3]/div[2]/div/div/div[1]/div[3]"
DRAWING = "//*[@id='root']/div[5]/div/div[2]/div/div[2]/div/div/div[2]/div[2]/div[3]/div[2]/div/div/div[1]/div[2]/div"
MNAME = "//input[@class='sc-dkPtRN dBqbgo input']"
SUBMIT = "//button[@class='sc-bdvvtL fSpYde submit']"
SUBMIT_DRAWING = "//button[normalize-space()='Submit']"
UPLOAD_PACKAGE = "//button[@class='sc-bdvvtL fSpYde']"
CANCEL_PACKAGE = "//button[normalize-space()='Cancel']"
JOB_NAME_LABEL = "//label[@class='wizard-content-label job-name']/span/span"
